flowchart LR
	%% Entry/End point
	API(API Start Point)
	Database[(Database)]

	%% Controllers
	TransactionController[Transaction Endpoint]
	TransactionRepository[Transaction Persistence]
	InvestmentPositionRepository[Investment Position]

	%% Use Cases
	CreateTransactionUseCase[Create Transaction UseCase]
	GetTransactionUseCase[Get Transaction UseCase]

	%% Helpers
	CreateTransactionValidator{Create Transaction Validator}
	NotValidException[Not Valid Exception]
	GetTransactionHasId{Has Id}

	%% Repository Functions
	CreateTransactionAsync[CreateTransactionAsyncFunc]
	GetByIdAsync[GetByIdAsyncFunc]
	GetAsyncFunc[GetAsyncFunc]
	BuyInvestment[BuyInvestiment]
	SellInvestment[SellInvestment]

	%% Standard one way flow
	API --> TransactionController
	TransactionRepository --> Database
	InvestmentPositionRepository --> Database

	subgraph Controller
		TransactionController --> CreateTransactionUseCase
		TransactionController --> GetTransactionUseCase
	end

	subgraph Repository
		CreateTransactionAsync --> TransactionRepository
		GetByIdAsync --> TransactionRepository
		GetAsyncFunc --> TransactionRepository

		BuyInvestiment --> InvestmentPositionRepository
		SellInvestment --> InvestmentPositionRepository
	end

	%% Create Flow
	CreateTransactionUseCase --> CreateTransactionValidator
	CreateTransactionValidator -->|Is Valid| CreateTransactionAsync
	CreateTransactionValidator -->|Is Not Valid| NotValidException
	NotValidException --> CreateTransactionUseCase

	%% Get Flow
	GetTransactionUseCase --> GetTransactionHasId
	GetTransactionHasId -->|Yes| GetByIdAsync
	GetTransactionHasId -->|No| GetAsyncFunc

	%% Investment
	Controller --> SellUseCase
	SellUseCase --> InvestmentPosition
	InvestmentPosition -->|Calculate Profit| TaxStrategy
	TaxStrategy -->|Calculate Tax| SellResult